# coding: utf-8
from __future__ import print_function
from __future__ import unicode_literals

"""a lookup table mapping language names to ISO 690-1 codes"""

language_codes = {
    "AA": "Afar",
    "AB": "Abkhazian",
    "AE": "Avestan",
    "AF": "Afrikaans",
    "AK": "Akan",
    "AM": "Amharic",
    "AN": "Aragonese",
    "AR": "Arabic",
    "AS": "Assamese",
    "AV": "Avaric",
    "AY": "Aymara",
    "AZ": "Azerbaijani",
    "BA": "Bashkir",
    "BE": "Belarusian",
    "BG": "Bulgarian",
    "BH": "Bihari",
    "BI": "Bislama",
    "BM": "Bambara",
    "BN": "Bengali",
    "BO": "Tibetan",
    "BR": "Breton",
    "BS": "Bosnian",
    "CA": "Catalan",
    "CE": "Chechen",
    "CH": "Chamorro",
    "CO": "Corsican",
    "CR": "Cree",
    "CS": "Czech",
    "CU": "Church Slavic",
    "CV": "Chuvash",
    "CY": "Welsh",
    "DA": "Danish",
    "DE": "German",
    "DV": "Divehi, Dhivehi, Maldivian",
    "DZ": "Dzongkha",
    "EE": "Ewe",
    "EL": "Modern Greek",
    "EN": "English",
    "EO": "Esperanto",
    "ES": "Spanish, Castilian",
    "ET": "Estonian",
    "EU": "Basque",
    "FA": "Persian",
    "FF": "Fulah",
    "FI": "Finnish",
    "FJ": "Fijian",
    "FO": "Faroese",
    "FR": "French",
    "FY": "Western Frisian",
    "GA": "Irish",
    "GD": "Gaelic, Scottish Gaelic",
    "GL": "Galician",
    "GN": "Guaraní",
    "GU": "Gujarati",
    "GV": "Manx",
    "HA": "Hausa",
    "HE": "Modern Hebrew",
    "HI": "Hindi",
    "HO": "Hiri Motu",
    "HR": "Croatian",
    "HT": "Haitian, Haitian Creole",
    "HU": "Hungarian",
    "HY": "Armenian",
    "HZ": "Herero",
    "IA": "Interlingua",
    "ID": "Indonesian",
    "IE": "Interlingue, Occidental",
    "IG": "Igbo",
    "II": "Sichuan Yi, Nuosu",
    "IK": "Inupiaq",
    "IO": "Ido",
    "IS": "Icelandic",
    "IT": "Italian",
    "IU": "Inuktitut",
    "JA": "Japanese",
    "JV": "Javanese",
    "KA": "Georgian",
    "KG": "Kongo",
    "KI": "Kikuyu, Gikuyu",
    "KJ": "Kwanyama, Kuanyama",
    "KK": "Kazakh",
    "KL": "Kalaallisut, Greenlandic",
    "KM": "Central Khmer",
    "KN": "Kannada",
    "KO": "Korean",
    "KR": "Kanuri",
    "KS": "Kashmiri",
    "KU": "Kurdish",
    "KV": "Komi",
    "KW": "Cornish",
    "KY": "Kirghiz, Kyrgyz",
    "LA": "Latin",
    "LB": "Luxembourgish",
    "LG": "Ganda",
    "LI": "Limburgish",
    "LN": "Lingala",
    "LO": "Lao",
    "LT": "Lithuanian",
    "LU": "Luba-Katanga",
    "LV": "Latvian",
    "MG": "Malagasy",
    "MH": "Marshallese",
    "MI": "Māori",
    "MK": " SL Macedonian",
    "ML": "Malayalam",
    "MN": "Mongolian",
    "MO": "Moldavian",
    "MR": "Marathi",
    "MS": "Malay",
    "MT": "Maltese",
    "MY": "Burmese",
    "NA": "Nauru",
    "NB": "Norwegian Bokmål",
    "ND": "North Ndebele",
    "NE": "Nepali",
    "NG": "Ndonga",
    "NL": "Dutch",
    "NN": "Norwegian Nynorsk",
    "NO": "Norwegian",
    "NR": "South Ndebele",
    "NV": "Navaj",
    "NY": "Chichewa, Chewa, Nyanja",
    "OC": "Occitan (after 1500)",
    "OJ": "Ojibwa",
    "OM": "Oromo",
    "OR": "Oriya",
    "OS": "Ossetian",
    "PA": "Punjabi",
    "PI": "Pāli",
    "PL": "Polish",
    "PS": "Pashto",
    "PT": "Portuguese",
    "QU": "Quechua",
    "RM": "Romansh",
    "RN": "Rundi",
    "RO": "Romanian, Moldavian, Moldovan",
    "RU": "Russian",
    "RW": "Kinyarwanda",
    "SA": "Sanskrit",
    "SC": "Sardinian",
    "SD": "Sindhi",
    "SE": "Northern Sami",
    "SG": "Sango",
    "SH": "Serbo-Croatian",
    "SI": "Sinhala",
    "SK": "Slovak",
    "SL": "Slovene",
    "SM": "Samoan",
    "SN": "Shona",
    "SO": "Somali",
    "SQ": "Albanian",
    "SR": "Serbian",
    "SS": "Swati",
    "ST": "Southern Sotho",
    "SU": "Sundanese",
    "SV": "Swedish",
    "SW": "Swahili",
    "TA": "Tamil",
    "TE": "Telugu",
    "TG": "Tajik",
    "TH": "Thai",
    "TI": "Tigrinya",
    "TK": "Turkmen",
    "TL": "Tagalog",
    "TN": "Tswana",
    "TO": "Tonga (Tonga Islands)",
    "TR": "Turkish",
    "TS": "Tsonga",
    "TT": "Tatar",
    "TW": "Twi",
    "TY": "Tahitian",
    "UG": "Uighur, Uyghur",
    "UK": "Ukrainian",
    "UR": "Urdu",
    "UZ": "Uzbek",
    "VE": "Venda",
    "VI": "Vietnamese",
    "VO": "Volapük",
    "WA": "Walloon",
    "WO": "Wolof",
    "XH": "Xhosa",
    "YI": "Yiddish",
    "YO": "Yoruba",
    "ZA": "Zhuang, Chuang",
    "ZH": "Chinese",
    "ZU": "Zulu"
}


def language_name(code):
    return language_codes.get(code.upper()) or code


def main():
    pass


if __name__ == "__main__":
    main()
